name: Build

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
    paths-ignore:
      - "README.md"

  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      CC: "gcc-13"
      CXX: "g++-13"
      LDFLAGS: "-static-libstdc++ -static-libgcc -Wl,-rpath=/opt/vacon/lib -Wl,--disable-new-dtags"
      PKG_CONFIG_PATH: "/opt/vacon/lib/pkgconfig"
      CMAKE: "cmake -Wno-dev"

    steps:
    - name: Checkout Vacon
      uses: actions/checkout@v4

    - name: Checkout SDL3
      uses: actions/checkout@v4
      with:
        repository: libsdl-org/SDL
        ref: "99f6bcf5049ba7d536f8e5b94de818618a47814e"
        path: sdl

    - name: Checkout FFmpeg
      uses: actions/checkout@v4
      with:
        repository: FFmpeg/FFmpeg
        ref: "n6.1.1"
        path: ffmpeg

    - name: Install meson and ninja
      run: |
        sudo pip install meson ninja

    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends -V \
          build-essential \
          ca-certificates \
          chrpath \
          cmake \
          debhelper \
          git \
          libdrm-dev \
          libdwarf-dev \
          libegl-dev \
          libelf-dev \
          libfontconfig-dev \
          libopengl-dev \
          libssl-dev \
          libunwind-dev \
          libva-dev \
          libvpl-dev \
          libvpl2 \
          libwayland-dev \
          libxkbcommon-dev \
          linux-libc-dev \
          meson \
          ninja-build \
          pkg-config \
          wayland-protocols \
        ;

    - name: Configure package manager with Debian sources
      run: |
        sudo apt-get install -y --no-install-recommends -V debian-archive-keyring
        sudo ln -sf /usr/share/keyrings/debian-archive-keyring.gpg /etc/apt/trusted.gpg.d/
        echo "deb http://deb.debian.org/debian/ sid main" | sudo tee /etc/apt/sources.list.d/debian-sid.list
        echo "deb-src http://deb.debian.org/debian/ experimental main" | sudo tee /etc/apt/sources.list.d/debian-experimental.list
        echo -e "Package: *\nPin: release o=Debian\nPin-Priority: -10" | sudo tee /etc/apt/preferences.d/99-local-debian
        sudo apt-get update

    - name: Install libsdl3 build dependencies
      run: |
        sudo apt-get install -y --no-install-recommends -V libdecor-0-dev/unstable
        sudo apt-get build-dep -y libsdl3-dev
        sudo dpkg -P libdecor-0-0 libdecor-0-dev

    - name: Build SDL3
      working-directory: "./sdl"
      run: |
        cmake -B build -G Ninja \
          -DCMAKE_INSTALL_PREFIX=/opt/vacon \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DCMAKE_C_FLAGS_RELWITHDEBINFO="-O2 -ggdb3 -fno-omit-frame-pointer" \
          -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF \
          -DCMAKE_INSTALL_RUNSTATEDIR=/run \
          -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON \
          -DSDL_ALSA_SHARED=OFF \
          -DSDL_DISABLE_INSTALL_DOCS=ON \
          -DSDL_HAPTIC_DEFAULT=OFF \
          -DSDL_HIDAPI_DEFAULT=OFF \
          -DSDL_HIDAPI_LIBUSB_SHARED=OFF \
          -DSDL_INSTALL_TESTS=ON \
          -DSDL_JACK=OFF \
          -DSDL_JACK_SHARED=OFF \
          -DSDL_JOYSTICK_DEFAULT=OFF \
          -DSDL_KMSDRM_SHARED=OFF \
          -DSDL_OSS=OFF \
          -DSDL_PIPEWIRE_SHARED=ON \
          -DSDL_POWER_DEFAULT=OFF \
          -DSDL_PULSEAUDIO_SHARED=OFF \
          -DSDL_RPATH=OFF \
          -DSDL_RPI=OFF \
          -DSDL_SENSOR_DEFAULT=OFF \
          -DSDL_SHARED=ON \
          -DSDL_STATIC=OFF \
          -DSDL_TESTS=OFF \
          -DSDL_TEST_LIBRARY=OFF \
          -DSDL_VIDEO_CAPTURE=OFF \
          -DSDL_VIVANTE=OFF \
          -DSDL_WAYLAND=ON \
          -DSDL_WAYLAND_SHARED=OFF \
          -DSDL_X11=ON \
          -DSDL_X11_SHARED=OFF \
        ;
        ninja -v -C build
        sudo ninja -C build install

    - name: Build FFmpeg
      working-directory: "./ffmpeg"
      run: |
        mkdir build
        cd build
        $(pwd)/../configure \
          --prefix=/opt/vacon \
          --cc=gcc-13 \
          --cxx=g++-13 \
          --disable-everything \
          --enable-avcodec \
          --enable-avfilter \
          --enable-avformat \
          --enable-avutil \
          --enable-decoder=rawvideo \
          --enable-demuxer=av1 \
          --enable-demuxer=h264 \
          --enable-demuxer=hevc \
          --enable-demuxer=mjpeg \
          --enable-demuxer=rawvideo \
          --enable-demuxer=rtp \
          --enable-demuxer=rtsp \
          --enable-encoder=av1_vaapi \
          --enable-encoder=h264_vaapi \
          --enable-encoder=hevc_vaapi \
          --enable-encoder=rawvideo \
          --enable-encoder=vp9_vaapi \
          --enable-filter=hwdownload \
          --enable-filter=hwmap \
          --enable-filter=hwupload \
          --enable-filter=scale_vaapi \
          --enable-hwaccel=av1_vaapi \
          --enable-hwaccel=h264_vaapi \
          --enable-hwaccel=hevc_vaapi \
          --enable-hwaccel=mjpeg_vaapi \
          --enable-hwaccel=vp9_vaapi \
          --enable-libdrm \
          --enable-muxer=h264 \
          --enable-muxer=hevc \
          --enable-muxer=rawvideo \
          --enable-muxer=rtp \
          --enable-muxer=rtsp \
          --enable-parser=av1 \
          --enable-parser=h264 \
          --enable-parser=hevc \
          --enable-parser=mjpeg \
          --enable-parser=vp9 \
          --enable-pixelutils \
          --enable-protocol=file \
          --enable-protocol=rtp \
          --enable-pthreads \
          --enable-vaapi \
          --disable-dwt \
          --disable-error-resilience \
          --disable-faan \
          --disable-iconv \
          --disable-lsp \
          --disable-postproc \
          --disable-swresample \
          --disable-swscale \
          --disable-x86asm \
          --disable-doc \
          --disable-htmlpages \
          --disable-manpages \
          --disable-podpages \
          --disable-txtpages \
          --disable-bzlib \
          --disable-libxcb \
          --disable-libxcb_shm \
          --disable-lzma \
          --disable-xlib \
          --disable-zlib \
        ;
        make -j$(nproc)
        sudo make install
        sudo rm -vrf /opt/vacon/share/ffmpeg

    - name: Build Vacon
      run: |
        meson setup build --default-library static --wrap-mode forcefallback --prefix /opt/vacon --libdir lib
        meson compile -v -C build
        chrpath --replace /opt/vacon/lib build/vacon
        mkdir -p /opt/vacon/bin
        sudo install -m 0755 build/vacon /opt/vacon/bin/vacon

    - name: Prepare Debian packaging
      run: |
        if [ "$GITHUB_REF_TYPE" = "tag" ]; then
          VERSION="$(echo $GITHUB_REF_NAME | sed -e 's/^v//')"
        else
          VERSION="0"
        fi
        VERSION="$VERSION+$(date +%Y%m%d)+git$(git rev-parse --short HEAD)"
        echo "VERSION is $VERSION"
        mkdir -p ./deb/vacon/opt
        cp -av /opt/vacon ./deb/vacon/opt/
        cp -av .packaging/debian ./deb/vacon
        sed \
          -e "s,%VERSION%,$VERSION,g" \
          -e "s/%USER%/$(whoami)/g" \
          -e "s/%NODE%/$(uname -n)/g" \
          -e "s/%DATE%/$(date -R)/g" \
          ./deb/vacon/debian/changelog.in > ./deb/vacon/debian/changelog

    - name: Build Debian package
      working-directory: "./deb/vacon"
      run: |
        dpkg-buildpackage -B -us -uc

    - name: Inspect Debian package
      working-directory: "./deb"
      run: |
        dpkg-deb -I vacon_*.deb
        dpkg-deb -c vacon_*.deb

    - name: Upload Debian package to artifact storage
      uses: actions/upload-artifact@v4
      with:
        name: binary-vacon-deb
        path: deb/vacon_*.deb
        compression-level: 0

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          deb/vacon_*.deb
        fail_on_unmatched_files: true
